/*
@module  lvgl
@summary LVGL常量定义
@version 2.0
@date    2026.06.18
@author  杰神 & TRAE & ChatGPT
*/

#include "lvgl.h"
#include "lvgl_obj.h"

/* 定义常量 */
void lvgl_define_constants(lua_State* L) {
    /* 对齐方式 */
    REG_CONSTANT(L, "ALIGN_DEFAULT", LV_ALIGN_DEFAULT);
    REG_CONSTANT(L, "ALIGN_TOP_LEFT", LV_ALIGN_TOP_LEFT);
    REG_CONSTANT(L, "ALIGN_TOP_MID", LV_ALIGN_TOP_MID);
    REG_CONSTANT(L, "ALIGN_TOP_RIGHT", LV_ALIGN_TOP_RIGHT);
    REG_CONSTANT(L, "ALIGN_BOTTOM_LEFT", LV_ALIGN_BOTTOM_LEFT);
    REG_CONSTANT(L, "ALIGN_BOTTOM_MID", LV_ALIGN_BOTTOM_MID);
    REG_CONSTANT(L, "ALIGN_BOTTOM_RIGHT", LV_ALIGN_BOTTOM_RIGHT);
    REG_CONSTANT(L, "ALIGN_LEFT_MID", LV_ALIGN_LEFT_MID);
    REG_CONSTANT(L, "ALIGN_RIGHT_MID", LV_ALIGN_RIGHT_MID);
    REG_CONSTANT(L, "ALIGN_CENTER", LV_ALIGN_CENTER);

    /* 状态 */
    REG_CONSTANT(L, "STATE_DEFAULT", LV_STATE_DEFAULT);
    REG_CONSTANT(L, "STATE_CHECKED", LV_STATE_CHECKED);
    REG_CONSTANT(L, "STATE_FOCUSED", LV_STATE_FOCUSED);
    REG_CONSTANT(L, "STATE_EDITED", LV_STATE_EDITED);
    REG_CONSTANT(L, "STATE_HOVERED", LV_STATE_HOVERED);
    REG_CONSTANT(L, "STATE_PRESSED", LV_STATE_PRESSED);
    REG_CONSTANT(L, "STATE_DISABLED", LV_STATE_DISABLED);

    /* 部分 */
    REG_CONSTANT(L, "PART_MAIN", LV_PART_MAIN);
    REG_CONSTANT(L, "PART_SCROLLBAR", LV_PART_SCROLLBAR);
    REG_CONSTANT(L, "PART_INDICATOR", LV_PART_INDICATOR);
    REG_CONSTANT(L, "PART_KNOB", LV_PART_KNOB);
    REG_CONSTANT(L, "PART_SELECTED", LV_PART_SELECTED);
    REG_CONSTANT(L, "PART_ITEMS", LV_PART_ITEMS);
    REG_CONSTANT(L, "PART_TICKS", LV_PART_TICKS);
    REG_CONSTANT(L, "PART_CURSOR", LV_PART_CURSOR);

    /* 动画 */
    REG_CONSTANT(L, "ANIM_OFF", LV_ANIM_OFF);
    REG_CONSTANT(L, "ANIM_ON", LV_ANIM_ON);

    /* 动画路径 */
    REG_CONSTANT(L, "ANIM_PATH_LINEAR", 0);
    REG_CONSTANT(L, "ANIM_PATH_EASE_IN", 1);
    REG_CONSTANT(L, "ANIM_PATH_EASE_OUT", 2);
    REG_CONSTANT(L, "ANIM_PATH_EASE_IN_OUT", 3);
    REG_CONSTANT(L, "ANIM_PATH_OVERSHOOT", 4);
    REG_CONSTANT(L, "ANIM_PATH_BOUNCE", 5);
    REG_CONSTANT(L, "ANIM_PATH_STEP", 6);

    /* 透明度 */
    REG_CONSTANT(L, "OPA_TRANSP", LV_OPA_TRANSP);
    REG_CONSTANT(L, "OPA_0", LV_OPA_0);
    REG_CONSTANT(L, "OPA_10", LV_OPA_10);
    REG_CONSTANT(L, "OPA_20", LV_OPA_20);
    REG_CONSTANT(L, "OPA_30", LV_OPA_30);
    REG_CONSTANT(L, "OPA_40", LV_OPA_40);
    REG_CONSTANT(L, "OPA_50", LV_OPA_50);
    REG_CONSTANT(L, "OPA_60", LV_OPA_60);
    REG_CONSTANT(L, "OPA_70", LV_OPA_70);
    REG_CONSTANT(L, "OPA_80", LV_OPA_80);
    REG_CONSTANT(L, "OPA_90", LV_OPA_90);
    REG_CONSTANT(L, "OPA_100", LV_OPA_100);
    REG_CONSTANT(L, "OPA_COVER", LV_OPA_COVER);

    /* 文本对齐 */
    REG_CONSTANT(L, "TEXT_ALIGN_LEFT", LV_TEXT_ALIGN_LEFT);
    REG_CONSTANT(L, "TEXT_ALIGN_CENTER", LV_TEXT_ALIGN_CENTER);
    REG_CONSTANT(L, "TEXT_ALIGN_RIGHT", LV_TEXT_ALIGN_RIGHT);
    REG_CONSTANT(L, "TEXT_ALIGN_AUTO", LV_TEXT_ALIGN_AUTO);

    /* 边框边 */
    REG_CONSTANT(L, "BORDER_SIDE_NONE", LV_BORDER_SIDE_NONE);
    REG_CONSTANT(L, "BORDER_SIDE_BOTTOM", LV_BORDER_SIDE_BOTTOM);
    REG_CONSTANT(L, "BORDER_SIDE_TOP", LV_BORDER_SIDE_TOP);
    REG_CONSTANT(L, "BORDER_SIDE_LEFT", LV_BORDER_SIDE_LEFT);
    REG_CONSTANT(L, "BORDER_SIDE_RIGHT", LV_BORDER_SIDE_RIGHT);
    REG_CONSTANT(L, "BORDER_SIDE_FULL", LV_BORDER_SIDE_FULL);
    REG_CONSTANT(L, "BORDER_SIDE_INTERNAL", LV_BORDER_SIDE_INTERNAL);

    /* 渐变方向 */
    REG_CONSTANT(L, "GRAD_DIR_NONE", LV_GRAD_DIR_NONE);
    REG_CONSTANT(L, "GRAD_DIR_VER", LV_GRAD_DIR_VER);
    REG_CONSTANT(L, "GRAD_DIR_HOR", LV_GRAD_DIR_HOR);

    /* Flex布局 */
    REG_CONSTANT(L, "FLEX_FLOW_ROW", LV_FLEX_FLOW_ROW);
    REG_CONSTANT(L, "FLEX_FLOW_COLUMN", LV_FLEX_FLOW_COLUMN);
    REG_CONSTANT(L, "FLEX_FLOW_ROW_WRAP", LV_FLEX_FLOW_ROW_WRAP);
    REG_CONSTANT(L, "FLEX_FLOW_COLUMN_WRAP", LV_FLEX_FLOW_COLUMN_WRAP);
    REG_CONSTANT(L, "FLEX_FLOW_ROW_REVERSE", LV_FLEX_FLOW_ROW_REVERSE);
    REG_CONSTANT(L, "FLEX_FLOW_COLUMN_REVERSE", LV_FLEX_FLOW_COLUMN_REVERSE);
    REG_CONSTANT(L, "FLEX_FLOW_ROW_WRAP_REVERSE", LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    REG_CONSTANT(L, "FLEX_FLOW_COLUMN_WRAP_REVERSE", LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);

    REG_CONSTANT(L, "FLEX_ALIGN_START", LV_FLEX_ALIGN_START);
    REG_CONSTANT(L, "FLEX_ALIGN_END", LV_FLEX_ALIGN_END);
    REG_CONSTANT(L, "FLEX_ALIGN_CENTER", LV_FLEX_ALIGN_CENTER);
    REG_CONSTANT(L, "FLEX_ALIGN_SPACE_EVENLY", LV_FLEX_ALIGN_SPACE_EVENLY);
    REG_CONSTANT(L, "FLEX_ALIGN_SPACE_AROUND", LV_FLEX_ALIGN_SPACE_AROUND);
    REG_CONSTANT(L, "FLEX_ALIGN_SPACE_BETWEEN", LV_FLEX_ALIGN_SPACE_BETWEEN);

    /* Grid布局 */
    REG_CONSTANT(L, "GRID_ALIGN_START", LV_GRID_ALIGN_START);
    REG_CONSTANT(L, "GRID_ALIGN_END", LV_GRID_ALIGN_END);
    REG_CONSTANT(L, "GRID_ALIGN_CENTER", LV_GRID_ALIGN_CENTER);
    REG_CONSTANT(L, "GRID_ALIGN_STRETCH", LV_GRID_ALIGN_STRETCH);
    REG_CONSTANT(L, "GRID_ALIGN_SPACE_EVENLY", LV_GRID_ALIGN_SPACE_EVENLY);
    REG_CONSTANT(L, "GRID_ALIGN_SPACE_AROUND", LV_GRID_ALIGN_SPACE_AROUND);
    REG_CONSTANT(L, "GRID_ALIGN_SPACE_BETWEEN", LV_GRID_ALIGN_SPACE_BETWEEN);

    /* 输入设备类型 */
    REG_CONSTANT(L, "INDEV_TYPE_NONE", LV_INDEV_TYPE_NONE);
    REG_CONSTANT(L, "INDEV_TYPE_POINTER", LV_INDEV_TYPE_POINTER);
    REG_CONSTANT(L, "INDEV_TYPE_KEYPAD", LV_INDEV_TYPE_KEYPAD);
    REG_CONSTANT(L, "INDEV_TYPE_BUTTON", LV_INDEV_TYPE_BUTTON);
    REG_CONSTANT(L, "INDEV_TYPE_ENCODER", LV_INDEV_TYPE_ENCODER);

    /* 滚动条模式 */
    REG_CONSTANT(L, "SCROLLBAR_MODE_OFF", LV_SCROLLBAR_MODE_OFF);
    REG_CONSTANT(L, "SCROLLBAR_MODE_ON", LV_SCROLLBAR_MODE_ON);
    REG_CONSTANT(L, "SCROLLBAR_MODE_ACTIVE", LV_SCROLLBAR_MODE_ACTIVE);
    REG_CONSTANT(L, "SCROLLBAR_MODE_AUTO", LV_SCROLLBAR_MODE_AUTO);

    /* 滚动方向 */
    REG_CONSTANT(L, "DIR_NONE", LV_DIR_NONE);
    REG_CONSTANT(L, "DIR_LEFT", LV_DIR_LEFT);
    REG_CONSTANT(L, "DIR_RIGHT", LV_DIR_RIGHT);
    REG_CONSTANT(L, "DIR_TOP", LV_DIR_TOP);
    REG_CONSTANT(L, "DIR_BOTTOM", LV_DIR_BOTTOM);
    REG_CONSTANT(L, "DIR_HOR", LV_DIR_HOR);
    REG_CONSTANT(L, "DIR_VER", LV_DIR_VER);
    REG_CONSTANT(L, "DIR_ALL", LV_DIR_ALL);

    /* 基础颜色 */
    REG_CONSTANT(L, "COLOR_BLACK", lv_color_black().full);
    REG_CONSTANT(L, "COLOR_WHITE", lv_color_white().full);
    REG_CONSTANT(L, "COLOR_RED", lv_color_red().full);
    REG_CONSTANT(L, "COLOR_GREEN", lv_color_green().full);
    REG_CONSTANT(L, "COLOR_BLUE", lv_color_blue().full);
    REG_CONSTANT(L, "COLOR_YELLOW", lv_color_yellow().full);
    REG_CONSTANT(L, "COLOR_ORANGE", lv_color_orange().full);
    REG_CONSTANT(L, "COLOR_PURPLE", lv_color_purple().full);
    REG_CONSTANT(L, "COLOR_CYAN", lv_color_cyan().full);
    REG_CONSTANT(L, "COLOR_GRAY", lv_color_gray().full);
    REG_CONSTANT(L, "COLOR_LIGHT_GRAY", lv_color_light_gray().full);
    REG_CONSTANT(L, "COLOR_DARK_GRAY", lv_color_dark_gray().full);

    /* 尺寸特殊值 */
    REG_CONSTANT(L, "SIZE_CONTENT", LV_SIZE_CONTENT);
    REG_CONSTANT(L, "PCT", LV_PCT);

    /* 坐标特殊值 */
    REG_CONSTANT(L, "COORD_MAX", LV_COORD_MAX);
    REG_CONSTANT(L, "COORD_MIN", LV_COORD_MIN);

    /* 动画无限重复 */
    REG_CONSTANT(L, "ANIM_REPEAT_INFINITE", LV_ANIM_REPEAT_INFINITE);

    /* 按钮状态 */
    REG_CONSTANT(L, "BTN_STATE_NONE", LV_BTN_STATE_NONE);
    REG_CONSTANT(L, "BTN_STATE_RELEASED", LV_BTN_STATE_RELEASED);
    REG_CONSTANT(L, "BTN_STATE_PRESSED", LV_BTN_STATE_PRESSED);
    REG_CONSTANT(L, "BTN_STATE_CHECKED_RELEASED", LV_BTN_STATE_CHECKED_RELEASED);
    REG_CONSTANT(L, "BTN_STATE_CHECKED_PRESSED", LV_BTN_STATE_CHECKED_PRESSED);
    REG_CONSTANT(L, "BTN_STATE_DISABLED", LV_BTN_STATE_DISABLED);
    REG_CONSTANT(L, "BTN_STATE_CHECKED_DISABLED", LV_BTN_STATE_CHECKED_DISABLED);

    /* 标签长模式 */
    REG_CONSTANT(L, "LABEL_LONG_SCROLL", LV_LABEL_LONG_SCROLL);
    REG_CONSTANT(L, "LABEL_LONG_DOT", LV_LABEL_LONG_DOT);
    REG_CONSTANT(L, "LABEL_LONG_SCROLL_CIRCULAR", LV_LABEL_LONG_SCROLL_CIRCULAR);
    REG_CONSTANT(L, "LABEL_LONG_CROP", LV_LABEL_LONG_CROP);
    REG_CONSTANT(L, "LABEL_LONG_WRAP", LV_LABEL_LONG_WRAP);
    REG_CONSTANT(L, "LABEL_LONG_EXPAND", LV_LABEL_LONG_EXPAND);
    REG_CONSTANT(L, "LABEL_LONG_HIERARCHY", LV_LABEL_LONG_HIERARCHY);

    /* 下拉菜单方向 */
    REG_CONSTANT(L, "DROPDOWN_DIR_BOTTOM", LV_DIR_BOTTOM);
    REG_CONSTANT(L, "DROPDOWN_DIR_TOP", LV_DIR_TOP);
    REG_CONSTANT(L, "DROPDOWN_DIR_LEFT", LV_DIR_LEFT);
    REG_CONSTANT(L, "DROPDOWN_DIR_RIGHT", LV_DIR_RIGHT);

    /* 图表类型 */
    REG_CONSTANT(L, "CHART_TYPE_NONE", LV_CHART_TYPE_NONE);
    REG_CONSTANT(L, "CHART_TYPE_LINE", LV_CHART_TYPE_LINE);
    REG_CONSTANT(L, "CHART_TYPE_BAR", LV_CHART_TYPE_BAR);
    REG_CONSTANT(L, "CHART_TYPE_SCATTER", LV_CHART_TYPE_SCATTER);

    /* 图表轴 */
    REG_CONSTANT(L, "CHART_AXIS_PRIMARY_Y", LV_CHART_AXIS_PRIMARY_Y);
    REG_CONSTANT(L, "CHART_AXIS_SECONDARY_Y", LV_CHART_AXIS_SECONDARY_Y);
    REG_CONSTANT(L, "CHART_AXIS_PRIMARY_X", LV_CHART_AXIS_PRIMARY_X);
    REG_CONSTANT(L, "CHART_AXIS_SECONDARY_X", LV_CHART_AXIS_SECONDARY_X);

    /* 图表更新模式 */
    REG_CONSTANT(L, "CHART_UPDATE_MODE_SHIFT", LV_CHART_UPDATE_MODE_SHIFT);
    REG_CONSTANT(L, "CHART_UPDATE_MODE_CIRCULAR", LV_CHART_UPDATE_MODE_CIRCULAR);

    /* 滑块模式 */
    REG_CONSTANT(L, "SLIDER_MODE_NORMAL", LV_SLIDER_MODE_NORMAL);
    REG_CONSTANT(L, "SLIDER_MODE_SYMMETRICAL", LV_SLIDER_MODE_SYMMETRICAL);
    REG_CONSTANT(L, "SLIDER_MODE_RANGE", LV_SLIDER_MODE_RANGE);

    /* 旋转模式 */
    REG_CONSTANT(L, "ROT_NONE", LV_DISP_ROT_NONE);
    REG_CONSTANT(L, "ROT_90", LV_DISP_ROT_90);
    REG_CONSTANT(L, "ROT_180", LV_DISP_ROT_180);
    REG_CONSTANT(L, "ROT_270", LV_DISP_ROT_270);

    /* 布局 */
    REG_CONSTANT(L, "LAYOUT_NONE", LV_LAYOUT_NONE);
    REG_CONSTANT(L, "LAYOUT_FLEX", LV_LAYOUT_FLEX);
    REG_CONSTANT(L, "LAYOUT_GRID", LV_LAYOUT_GRID);
    REG_CONSTANT(L, "LAYOUT_COL_MID", LV_LAYOUT_COL_MID);
    REG_CONSTANT(L, "LAYOUT_COL_LEFT", LV_LAYOUT_COL_LEFT);
    REG_CONSTANT(L, "LAYOUT_COL_RIGHT", LV_LAYOUT_COL_RIGHT);
    REG_CONSTANT(L, "LAYOUT_ROW_MID", LV_LAYOUT_ROW_MID);
    REG_CONSTANT(L, "LAYOUT_ROW_LEFT", LV_LAYOUT_ROW_LEFT);
    REG_CONSTANT(L, "LAYOUT_ROW_RIGHT", LV_LAYOUT_ROW_RIGHT);
    REG_CONSTANT(L, "LAYOUT_CENTER", LV_LAYOUT_CENTER);
    REG_CONSTANT(L, "LAYOUT_PRETTY_MID", LV_LAYOUT_PRETTY_MID);
    REG_CONSTANT(L, "LAYOUT_PRETTY_TOP", LV_LAYOUT_PRETTY_TOP);
    REG_CONSTANT(L, "LAYOUT_GOOD_MID", LV_LAYOUT_GOOD_MID);
    REG_CONSTANT(L, "LAYOUT_GOOD_TOP", LV_LAYOUT_GOOD_TOP);

    /* Flex对齐方式 */
    REG_CONSTANT(L, "FLEX_SPACE_BETWEEN", LV_FLEX_ALIGN_SPACE_BETWEEN);
    REG_CONSTANT(L, "FLEX_SPACE_AROUND", LV_FLEX_ALIGN_SPACE_AROUND);
    REG_CONSTANT(L, "FLEX_SPACE_EVENLY", LV_FLEX_ALIGN_SPACE_EVENLY);

    /* Flex流动方向 */
    REG_CONSTANT(L, "FLEX_FLOW_ROW_WRAP", LV_FLEX_FLOW_ROW_WRAP);
    REG_CONSTANT(L, "FLEX_FLOW_COLUMN_WRAP", LV_FLEX_FLOW_COLUMN_WRAP);
    REG_CONSTANT(L, "FLEX_FLOW_ROW_REVERSE", LV_FLEX_FLOW_ROW_REVERSE);
    REG_CONSTANT(L, "FLEX_FLOW_COLUMN_REVERSE", LV_FLEX_FLOW_COLUMN_REVERSE);

    /* Grid对齐方式 */
    REG_CONSTANT(L, "GRID_SPACE_BETWEEN", LV_GRID_ALIGN_SPACE_BETWEEN);
    REG_CONSTANT(L, "GRID_SPACE_AROUND", LV_GRID_ALIGN_SPACE_AROUND);
    REG_CONSTANT(L, "GRID_SPACE_EVENLY", LV_GRID_ALIGN_SPACE_EVENLY);

    /* 对象标志 */
    REG_CONSTANT(L, "OBJ_FLAG_HIDDEN", LV_OBJ_FLAG_HIDDEN);
    REG_CONSTANT(L, "OBJ_FLAG_CLICKABLE", LV_OBJ_FLAG_CLICKABLE);
    REG_CONSTANT(L, "OBJ_FLAG_CLICK_FOCUSABLE", LV_OBJ_FLAG_CLICK_FOCUSABLE);
    REG_CONSTANT(L, "OBJ_FLAG_CHECKABLE", LV_OBJ_FLAG_CHECKABLE);
    REG_CONSTANT(L, "OBJ_FLAG_SCROLLABLE", LV_OBJ_FLAG_SCROLLABLE);
    REG_CONSTANT(L, "OBJ_FLAG_SCROLL_ELASTIC", LV_OBJ_FLAG_SCROLL_ELASTIC);
    REG_CONSTANT(L, "OBJ_FLAG_SCROLL_MOMENTUM", LV_OBJ_FLAG_SCROLL_MOMENTUM);
    REG_CONSTANT(L, "OBJ_FLAG_SCROLL_ONE", LV_OBJ_FLAG_SCROLL_ONE);
    REG_CONSTANT(L, "OBJ_FLAG_EVENT_BUBBLE", LV_OBJ_FLAG_EVENT_BUBBLE);
    REG_CONSTANT(L, "OBJ_FLAG_GESTURE_BUBBLE", LV_OBJ_FLAG_GESTURE_BUBBLE);
    REG_CONSTANT(L, "OBJ_FLAG_LAYOUT_1", LV_OBJ_FLAG_LAYOUT_1);
    REG_CONSTANT(L, "OBJ_FLAG_LAYOUT_2", LV_OBJ_FLAG_LAYOUT_2);
    REG_CONSTANT(L, "OBJ_FLAG_WIDGET_1", LV_OBJ_FLAG_WIDGET_1);
    REG_CONSTANT(L, "OBJ_FLAG_WIDGET_2", LV_OBJ_FLAG_WIDGET_2);
    REG_CONSTANT(L, "OBJ_FLAG_USER_1", LV_OBJ_FLAG_USER_1);
    REG_CONSTANT(L, "OBJ_FLAG_USER_2", LV_OBJ_FLAG_USER_2);
    REG_CONSTANT(L, "OBJ_FLAG_USER_3", LV_OBJ_FLAG_USER_3);
    REG_CONSTANT(L, "OBJ_FLAG_USER_4", LV_OBJ_FLAG_USER_4);
    REG_CONSTANT(L, "OBJ_FLAG_FLEX_IN_NEW_TRACK", LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);

    /* 复选框状态 */
    REG_CONSTANT(L, "CHECKBOX_STATE_CHECKED", LV_CHECKBOX_STATE_CHECKED);
    REG_CONSTANT(L, "CHECKBOX_STATE_UNCHECKED", LV_CHECKBOX_STATE_UNCHECKED);
    REG_CONSTANT(L, "CHECKBOX_STATE_DISABLED", LV_CHECKBOX_STATE_DISABLED);
    REG_CONSTANT(L, "CHECKBOX_STATE_INDETERMINATE", LV_CHECKBOX_STATE_INDETERMINATE);

    /* 下拉菜单位置 */
    REG_CONSTANT(L, "DROPDOWN_POS_LAST", LV_DROPDOWN_POS_LAST);

    /* 滚轮模式 */
    REG_CONSTANT(L, "ROLLER_MODE_NORMAL", LV_ROLLER_MODE_NORMAL);
    REG_CONSTANT(L, "ROLLER_MODE_INFINITE", LV_ROLLER_MODE_INFINITE);

    /* 图表系列类型 */
    REG_CONSTANT(L, "CHART_SERIES_TYPE_SHIFT", LV_CHART_SERIES_TYPE_SHIFT);
    REG_CONSTANT(L, "CHART_SERIES_TYPE_CIRCULAR", LV_CHART_SERIES_TYPE_CIRCULAR);

    /* 图片尺寸模式 */
    REG_CONSTANT(L, "IMG_SIZE_MODE_REAL", LV_IMG_SIZE_MODE_REAL);
    REG_CONSTANT(L, "IMG_SIZE_MODE_VIRTUAL", LV_IMG_SIZE_MODE_VIRTUAL);

    /* 对象类型 */
    REG_CONSTANT(L, "OBJ_TYPE_NULL", LV_OBJ_TYPE_NULL);
    REG_CONSTANT(L, "OBJ_TYPE_DROPDOWN_LIST", LV_OBJ_TYPE_DROPDOWN_LIST);
    REG_CONSTANT(L, "OBJ_TYPE_KEYBOARD", LV_OBJ_TYPE_KEYBOARD);
    REG_CONSTANT(L, "OBJ_TYPE_MESSAGE_BOX", LV_OBJ_TYPE_MESSAGE_BOX);

    /* ==================== 事件常量 ==================== */
    REG_CONSTANT(L, "EVENT_ALL", LV_EVENT_ALL);
    REG_CONSTANT(L, "EVENT_PRESSED", LV_EVENT_PRESSED);
    REG_CONSTANT(L, "EVENT_PRESSING", LV_EVENT_PRESSING);
    REG_CONSTANT(L, "EVENT_PRESS_LOST", LV_EVENT_PRESS_LOST);
    REG_CONSTANT(L, "EVENT_CLICKED", LV_EVENT_CLICKED);
    REG_CONSTANT(L, "EVENT_LONG_PRESSED", LV_EVENT_LONG_PRESSED);
    REG_CONSTANT(L, "EVENT_LONG_PRESSED_REPEAT", LV_EVENT_LONG_PRESSED_REPEAT);
    REG_CONSTANT(L, "EVENT_RELEASED", LV_EVENT_RELEASED);
    REG_CONSTANT(L, "EVENT_SCROLL_BEGIN", LV_EVENT_SCROLL_BEGIN);
    REG_CONSTANT(L, "EVENT_SCROLL_END", LV_EVENT_SCROLL_END);
    REG_CONSTANT(L, "EVENT_SCROLL", LV_EVENT_SCROLL);
    REG_CONSTANT(L, "EVENT_VALUE_CHANGED", LV_EVENT_VALUE_CHANGED);
    REG_CONSTANT(L, "EVENT_INSERT", LV_EVENT_INSERT);
    REG_CONSTANT(L, "EVENT_REFRESH", LV_EVENT_REFRESH);
    REG_CONSTANT(L, "EVENT_READY", LV_EVENT_READY);
    REG_CONSTANT(L, "EVENT_CANCEL", LV_EVENT_CANCEL);
    REG_CONSTANT(L, "EVENT_DELETE", LV_EVENT_DELETE);
    REG_CONSTANT(L, "EVENT_CHILD_CHANGED", LV_EVENT_CHILD_CHANGED);
    REG_CONSTANT(L, "EVENT_SCREEN_UNLOAD_START", LV_EVENT_SCREEN_UNLOAD_START);
    REG_CONSTANT(L, "EVENT_SCREEN_LOAD_START", LV_EVENT_SCREEN_LOAD_START);
    REG_CONSTANT(L, "EVENT_SCREEN_LOADED", LV_EVENT_SCREEN_LOADED);
    REG_CONSTANT(L, "EVENT_SCREEN_UNLOADED", LV_EVENT_SCREEN_UNLOADED);
    REG_CONSTANT(L, "EVENT_LAYOUT_CHANGED", LV_EVENT_LAYOUT_CHANGED);
    REG_CONSTANT(L, "EVENT_STYLE_CHANGED", LV_EVENT_STYLE_CHANGED);
    REG_CONSTANT(L, "EVENT_SIZE_CHANGED", LV_EVENT_SIZE_CHANGED);
    REG_CONSTANT(L, "EVENT_FOCUSED", LV_EVENT_FOCUSED);
    REG_CONSTANT(L, "EVENT_DEFOCUSED", LV_EVENT_DEFOCUSED);
    REG_CONSTANT(L, "EVENT_LEAVE", LV_EVENT_LEAVE);
    REG_CONSTANT(L, "EVENT_HIT_TEST", LV_EVENT_HIT_TEST);
    REG_CONSTANT(L, "EVENT_DRAW_MAIN_BEGIN", LV_EVENT_DRAW_MAIN_BEGIN);
    REG_CONSTANT(L, "EVENT_DRAW_MAIN_END", LV_EVENT_DRAW_MAIN_END);
    REG_CONSTANT(L, "EVENT_DRAW_POST_BEGIN", LV_EVENT_DRAW_POST_BEGIN);
    REG_CONSTANT(L, "EVENT_DRAW_POST_END", LV_EVENT_DRAW_POST_END);
    REG_CONSTANT(L, "EVENT_DRAW_PART_BEGIN", LV_EVENT_DRAW_PART_BEGIN);
    REG_CONSTANT(L, "EVENT_DRAW_PART_END", LV_EVENT_DRAW_PART_END);
    REG_CONSTANT(L, "EVENT_KEY", LV_EVENT_KEY);
    REG_CONSTANT(L, "EVENT_FOCUS_KEY", LV_EVENT_FOCUS_KEY);
    REG_CONSTANT(L, "EVENT_GESTURE", LV_EVENT_GESTURE);
    REG_CONSTANT(L, "EVENT_COVER_CHECK", LV_EVENT_COVER_CHECK);
    REG_CONSTANT(L, "EVENT_GET_SELF_SIZE", LV_EVENT_GET_SELF_SIZE);

    /* ==================== 键盘按键常量 ==================== */
    REG_CONSTANT(L, "KEY_NEXT", LV_KEY_NEXT);
    REG_CONSTANT(L, "KEY_PREV", LV_KEY_PREV);
    REG_CONSTANT(L, "KEY_UP", LV_KEY_UP);
    REG_CONSTANT(L, "KEY_DOWN", LV_KEY_DOWN);
    REG_CONSTANT(L, "KEY_LEFT", LV_KEY_LEFT);
    REG_CONSTANT(L, "KEY_RIGHT", LV_KEY_RIGHT);
    REG_CONSTANT(L, "KEY_ENTER", LV_KEY_ENTER);
    REG_CONSTANT(L, "KEY_ESC", LV_KEY_ESC);
    REG_CONSTANT(L, "KEY_DEL", LV_KEY_DEL);
    REG_CONSTANT(L, "KEY_BACKSPACE", LV_KEY_BACKSPACE);
    REG_CONSTANT(L, "KEY_TAB", LV_KEY_TAB);
    REG_CONSTANT(L, "KEY_HOME", LV_KEY_HOME);
    REG_CONSTANT(L, "KEY_END", LV_KEY_END);
    REG_CONSTANT(L, "KEY_PAGE_UP", LV_KEY_PAGE_UP);
    REG_CONSTANT(L, "KEY_PAGE_DOWN", LV_KEY_PAGE_DOWN);
    REG_CONSTANT(L, "KEY_PLAY", LV_KEY_PLAY);
    REG_CONSTANT(L, "KEY_PAUSE", LV_KEY_PAUSE);
    REG_CONSTANT(L, "KEY_STOP", LV_KEY_STOP);
    REG_CONSTANT(L, "KEY_FWD", LV_KEY_FWD);
    REG_CONSTANT(L, "KEY_BWD", LV_KEY_BWD);
    REG_CONSTANT(L, "KEY_VOLUME_UP", LV_KEY_VOLUME_UP);
    REG_CONSTANT(L, "KEY_VOLUME_DOWN", LV_KEY_VOLUME_DOWN);

    /* ==================== 手势常量 ==================== */
    REG_CONSTANT(L, "GESTURE_NONE", LV_GESTURE_NONE);
    REG_CONSTANT(L, "GESTURE_LEFT", LV_GESTURE_LEFT);
    REG_CONSTANT(L, "GESTURE_RIGHT", LV_GESTURE_RIGHT);
    REG_CONSTANT(L, "GESTURE_UP", LV_GESTURE_UP);
    REG_CONSTANT(L, "GESTURE_DOWN", LV_GESTURE_DOWN);

    /* ==================== 主题颜色ID ==================== */
    REG_CONSTANT(L, "THEME_COLOR_PRIMARY", LV_THEME_COLOR_PRIMARY);
    REG_CONSTANT(L, "THEME_COLOR_SECONDARY", LV_THEME_COLOR_SECONDARY);
    REG_CONSTANT(L, "THEME_COLOR_TERTIARY", LV_THEME_COLOR_TERTIARY);
    REG_CONSTANT(L, "THEME_COLOR_BACKGROUND", LV_THEME_COLOR_BACKGROUND);
    REG_CONSTANT(L, "THEME_COLOR_FOREGROUND", LV_THEME_COLOR_FOREGROUND);
    REG_CONSTANT(L, "THEME_COLOR_HIGHLIGHT", LV_THEME_COLOR_HIGHLIGHT);
    REG_CONSTANT(L, "THEME_COLOR_SELECTED", LV_THEME_COLOR_SELECTED);
    REG_CONSTANT(L, "THEME_COLOR_ERROR", LV_THEME_COLOR_ERROR);
    REG_CONSTANT(L, "THEME_COLOR_WARNING", LV_THEME_COLOR_WARNING);
    REG_CONSTANT(L, "THEME_COLOR_SUCCESS", LV_THEME_COLOR_SUCCESS);

    /* ==================== 主题字体ID ==================== */
    REG_CONSTANT(L, "THEME_FONT_SMALL", LV_THEME_FONT_SMALL);
    REG_CONSTANT(L, "THEME_FONT_MEDIUM", LV_THEME_FONT_MEDIUM);
    REG_CONSTANT(L, "THEME_FONT_LARGE", LV_THEME_FONT_LARGE);
    REG_CONSTANT(L, "THEME_FONT_TITLE", LV_THEME_FONT_TITLE);

    /* ==================== 主题尺寸ID ==================== */
    REG_CONSTANT(L, "THEME_SIZE_BUTTON_HEIGHT", LV_THEME_SIZE_BUTTON_HEIGHT);
    REG_CONSTANT(L, "THEME_SIZE_SLIDER_WIDTH", LV_THEME_SIZE_SLIDER_WIDTH);
    REG_CONSTANT(L, "THEME_SIZE_SLIDER_HEIGHT", LV_THEME_SIZE_SLIDER_HEIGHT);
}
