


#ifndef YOPEN_API_EVENT_DEF_H
#define YOPEN_API_EVENT_DEF_H

#include "yopen_api_common.h"


/***************************  task priority defination   ******************************/
typedef enum
{
	APP_PRIORITY_IDLE = 1, // reserved
    APP_PRIORITY_LOW = 4,
    APP_PRIORITY_BELOW_NORMAL = 8,
    APP_PRIORITY_NORMAL = 12,
    APP_PRIORITY_ABOVE_NORMAL = 16,
    APP_PRIORITY_HIGH = 25,
    APP_PRIORITY_REALTIME = 30  
}APP_ThreadPriority_e;



/****************************  error code about osi    ***************************/
typedef enum
{
	YOPEN_OSI_SUCCESS             =     0,
	
	YOPEN_OSI_TASK_PARAM_INVALID  =	 1 | (YOPEN_COMPONENT_OSI << 16),
	YOPEN_OSI_TASK_CREATE_FAIL,   
	YOPEN_OSI_NO_MEMORY,
	YOPEN_OSI_TASK_DELETE_FAIL,
	YOPEN_OSI_TASK_PRIO_INVALID,
	YOPEN_OSI_TASK_NAME_INVALID,
	YOPEN_OSI_TASK_EVENT_COUNT_INVALID,
	YOPEN_OSI_INVALID_TASK_REF,
	YOPEN_OSI_TASK_CNT_REACH_MAX,
	YOPEN_OSI_TASK_BIND_EVENT_FAIL,
	YOPEN_OSI_TASK_UNBIND_EVENT_FAIL,
	YOPEN_OSI_TASK_GET_REF_FAIL,
	YOPEN_OSI_TASK_GET_PRIO_FAIL,
	YOPEN_OSI_TASK_SET_PRIO_FAIL,
	YOPEN_OSI_TASK_GET_STATUS_FAIL,
	YOPEN_OSI_TASK_HAS_BINDED_TIMER,

	YOPEN_OSI_QUEUE_CREATE_FAIL	=   50 | (YOPEN_COMPONENT_OSI << 16), 
	YOPEN_OSI_QUEUE_DELETE_FAIL,
	YOPEN_OSI_QUEUE_IS_FULL,
	YOPEN_OSI_QUEUE_RELEASE_FAIL,
	YOPEN_OSI_QUEUE_RECEIVE_FAIL,
	YOPEN_OSI_QUEUE_GET_CNT_FAIL,
	YOPEN_OSI_QUEUE_IS_FAIL,
	YOPEN_OSI_QUEUE_RESET_FAIL,

	YOPEN_OSI_SEMA_CREATE_FAILE    =  100 | (YOPEN_COMPONENT_OSI << 16), 
	YOPEN_OSI_SEMA_DELETE_FAIL,
	YOPEN_OSI_SEMA_IS_FULL,
	YOPEN_OSI_SEMA_RELEASE_FAIL,
	YOPEN_OSI_SEMA_GET_FAIL,
	YOPEN_OSI_SEMA__FAIL,

	YOPEN_OSI_MUTEX_CREATE_FAIL	=  150 | (YOPEN_COMPONENT_OSI << 16), 
	YOPEN_OSI_MUTEX_DELETE_FAIL,
	YOPEN_OSI_MUTEX_LOCK_FAIL,
	YOPEN_OSI_MUTEX_UNLOCK_FAIL,

	YOPEN_OSI_EVENT_SEND_FAIL		=  200 | (YOPEN_COMPONENT_OSI << 16),
	YOPEN_OSI_EVENT_GET_FAIL,
	YOPEN_OSI_EVENT_REGISTER_FAIL,
	YOPEN_OSI_EVENT_PARAM_INVALID,

	YOPEN_OSI_TIMER_CREATE_FAIL	=  250 | (YOPEN_COMPONENT_OSI << 16),
	YOPEN_OSI_TIMER_START_FAIL,
	YOPEN_OSI_TIMER_STOP_FAIL,
	YOPEN_OSI_TIMER_DELETE_FAIL,
	YOPEN_OSI_TIMER_BIND_TASK_FAIL,

	YOPEN_OSI_SWDOG_REGISTER_FAIL  =  300 | (YOPEN_COMPONENT_OSI << 16),
	YOPEN_OSI_SWDOG_UNREGISTER_FAIL,
	YOPEN_OSI_SWDOG_FEED_DOG_FAIL,
	YOPEN_OSI_SWDOG_ENABLE_FAIL,
	YOPEN_OSI_SWDOG_DISABLE_FAIL,

}osi_errcode_e;


#endif
